# This YAML file defines two Kubernetes resources: a Deployment and a Service

---
# Deployment resource
apiVersion: apps/v1         # Specifies the version of the Kubernetes API to use for this resource
kind: Deployment            # Indicates that this is a Deployment resource
metadata:                   # Define Metadata
  name: book-catalog        # Sets the name of this Deployment
spec:                       # Begins the specification of the desired state for this Deployment
  replicas: 1               # Specifies that we want one copy of our pod running
  selector:                 # Defines how the Deployment finds which Pods to manage
    matchLabels:            # Match labels
      app: book-catalog     # Manages any pods with the label "app: book-catalog"
  template:                 # Describes the pod that will be created if insufficient replicas are detected
    metadata:               # Define template meta data
      labels:               # Define template labels
        app: book-catalog   # The label that will be applied to the Pod
    spec:                   # The specs for the Pod contents
      containers:           # List of containers to run in the Pod
      - name: book-catalog  # Name of the container
        image: book-catalog:latest  # The Docker image to use for this container
        ports:                      # List of ports to expose from the container
        - containerPort: 8000       # The port that the container is listening on
        env:                        # List of environment variables to set in the container
        - name: DATABASE_URL        # Name of the environment variable
          value: "postgresql://umair_sit722_part2_user:pGps9VGKhLq20r0sSIbYnXbA4E49Vf8l@dpg-cr6s0vtds78s73c3j950-a.oregon-postgres.render.com/umair_sit722_part2"  # Value of the environment variable

---
# Service resource
apiVersion: v1            # API version for the Service resource
kind: Service             # Specifies that this is a Service resource
metadata:                 # Define metadata of service
  name: book-catalog-service  # Sets name of Service
spec:                     # Begins the specification of the desired state for this Service
  selector:               # Defines selectors
    app: book-catalog     # Targets Pods with the label "app: book-catalog"
  ports:                  # Specify the list of ports that this Service should serve on
    - protocol: TCP       # The IP protocol for this port
      port: 80            # The port that the Service is exposed on
      targetPort: 8000    # The port on the Pod that the Service should direct traffic to
  type: LoadBalancer      # Specifies the type of Service -  exposes the Service externally using a cloud provider's load balancer
  